package com.shopsphere.model;

public enum ReturnStatus {

    RETURN_REQUESTED,
    REQUEST_APPROVED,
    PICKUP_SCHEDULED,
    PRODUCT_PICKED_UP,
    QUALITY_CHECK,
    REFUND_INITIATED,
    REFUND_COMPLETED,

    REPLACEMENT_REQUESTED,
    REPLACEMENT_APPROVED,
    REPLACEMENT_SHIPPED,
    REPLACEMENT_DELIVERED,

    REJECTED,
    CANCELLED
}
