# ---------------- Application ----------------
spring.application.name=shopsphere-backend
server.port=${PORT:8080}

# ---------------- Database ----------------
# ---------------- Database ----------------
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- JPA / Hibernate ----------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# ---------------- Razorpay ----------------
razorpay.key_id=${RAZORPAY_KEY_ID}
razorpay.key_secret=${RAZORPAY_KEY_SECRET}

# ---------------- Hibernate ----------------
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

# ---------------- Groq ----------------
groq.api-key=${GROQ_API_KEY}
groq.base-url=https://api.groq.com/openai/v1
groq.model=openai/gpt-oss-120b

# ---------------- Pexels ----------------
pexels.api.key=${PEXELS_API_KEY}

# ---------------- Logging ----------------
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# ---------------- Spring AI ----------------
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.image=none
spring.ai.model.moderation=none
spring.ai.model.chat=none