# ---------------- Application ----------------
spring.application.name=shopsphere-backend
server.port=8080

# ---------------- Database ----------------
spring.datasource.url=jdbc:postgresql://localhost:5432/pune
spring.datasource.username=postgres
spring.datasource.password=piyush
spring.datasource.driver-class-name=org.postgresql.Driver

# ---------------- JPA / Hibernate ----------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ---------------- Razorpay (FIXED) ----------------
razorpay.key_id=rzp_test_SiUqjfu32UIx4B
razorpay.key_secret=GxHcws5EL1CM1t0g2NosHDlJ

# Hibernate formatting
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
  


# ===============================
# GROQ AI CONFIGURATION
# ===============================

groq.api-key=${GROQ_API_KEY}
groq.base-url=https://api.groq.com/openai/v1
groq.model=openai/gpt-oss-120b
# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
pexels.api.key=PJhy5Ayxaq0Hpq6qH3k6Fl8MGlz4QI0Z1ZxYPvoUMuGTZzgSFq9Gj3em

# Disable Spring AI audio models
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.image=none
spring.ai.model.moderation=none

# We are using our own GroqService
spring.ai.model.chat=none

